---
title: "Create_Stimuli"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(stringr)
require(stats)
library(grid)
library(scales)
```

```{r}
library(readr)

# set wd to the folder this file is in

data <- read_csv("original_graph_data2.csv")
data <- data.frame(data)


```

# Functions to set up the data
```{r}

#get data sample 
get_graph_data_sample <- function(data, graphnumber){
  #number of bars
  number_bars <- c(3, 4, 5)
  sample <- sample(number_bars, 1)
  
  #filter data by graph number and number of bars
  graph_data <- data %>% 
    filter(graphcode == graphnumber)
  
  #choose the top x according to the value (for nominal variables) 
  #and according to the variables (for ordinal variables)
  #this prevents the issue of having non consecutive years in the x axis.
  if(graph_data$X.axis.order[1] == "none") {
    graph_data <- graph_data %>% 
      top_n(sample, Value)
  } else if(graph_data$X.axis.order[1] == "ordinal"){
    graph_data <- head(graph_data, sample)}
  else {
     graph_data <- graph_data %>% 
      top_n(sample, as.numeric(Variable))
  }  
  
  return(graph_data)
  
}

# Choose two bars to compare 
choose_2 <- function(graph_data){
 chosen_2 <- graph_data[sample(nrow(graph_data), 2), ]
 return(chosen_2)
}
```


# Functions to create graphs
```{r}
# finding minimum value, rounding down and cutting y axis there. 
get_cuttingat <- function(selected_rows, setGDI){
  
  d2 <- max(selected_rows$Value)
  d1 <- min(selected_rows$Value)

  b <- (d2-d1)/d1
  cuttingat <- d1 - ((d2-d1)/(b*((setGDI/100) +1)))
  #cuttingat <- min(data$Value)%/%10 * 10
  return(cuttingat)
}
```

```{r}
## This function plots a graph and a misleading graph and save each as a png. 
## Graph will be either 4, 5 or 6 bar
## Graph that is NOT time-series will be ordered either descending or ascending. 
## Misleading graph is plotted by according to get_cuttingat function

graph <- function(graph_data, selected_rows, graphnumber, accuracy, path, filename, highlight){
  
  #cutting at value for misleading graph
  cuttingat <- get_cuttingat(selected_rows, setGDI)
  #normal_distance <- max(graph_data$Value)-cuttingat
  #num_digits_normal_distance <- nchar(sub('\\..*$','',normal_distance))
  
  #bottom_break <- round(cuttingat,-(num_digits_normal_distance-1))
  #top_break <- round(max(graph_data$Value), -(num_digits_normal_distance-1))
  
  #distance <- top_break - bottom_break
  #num_digits_distance <- nchar(sub('\\..*$','',distance))
  #numb_ticks <- (distance / 10^(num_digits_distance-1))+1

  #distance_accurate <- top_break - 0
  #num_digits_distance_accurate <- nchar(sub('\\..*$','',distance_accurate))
  #numb_ticks_accurate <- (distance_accurate / 10^(num_digits_distance_accurate-1))+1

  #bar order
  barorder <- (-1) ^ graph_data$graphcode[1]
   
  #aesthetics
  mytheme <- theme(
     text =  element_text(family="Helvetica", size = 15, color = "#000000"),
     plot.title = element_text(margin = margin(b = 30)),
     axis.text = element_text(family="Helvetica", size = 16, color = "#000000"),
     axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
     axis.title.x = element_blank(),
     axis.line = element_line(size = 1, colour = "#000000"),
     panel.background = element_blank(),
     #panel.grid.minor = element_blank(), 
     aspect.ratio=0.5)
  
  #create graph
  g <- ggplot() + 
    mytheme + 
    geom_bar(data = graph_data, 
             aes(x = if(graph_data$X.axis.order != "ordered")
               {reorder(Variable, barorder*Value)}
               else{reorder(Variable, as.numeric(Variable))},
               y = Value), stat = "identity", 
             fill=rgb(0,0,0, maxColorValue = 255), width = 0.8) +
    ylab(graph_data$Y.axis.label)+
    xlab(graph_data$X.axis.label)+
    ggtitle(str_wrap(graph_data$Graph.Title, width = 150))+ 
    #ggtitle(graph_data$Graph.Title) + 
    scale_x_discrete(labels = function(x) str_wrap(x, width = 12))

#in case it's misleading
  if(accuracy == "misleading"){
  g <- g +
    coord_cartesian(xlim=c(1, nrow(graph_data)),
                    ylim=c(cuttingat,max(graph_data$Value)))+
    expand_limits(y=(c(0, max(graph_data$Value)))) +
    #scale_y_continuous(limits = c(bottom_break,top_break), breaks = seq(bottom_break,top_break, len = numb_ticks), oob = squish)
    scale_y_continuous(oob = squish, limits = c(cuttingat,max(graph_data$Value)))
    
  if (highlight == "highlight"){
      g <- g +  annotate('rect', xmin=0.2, xmax=0.5,
                         ymin=cuttingat, ymax=max(graph_data$Value), 
                         fill='yellow', alpha=1/3)
      # Convert into a grphical object -- a grob
      g <- ggplotGrob(g)
      i <- which(g$layout$name == 'panel')
      g$layout[i,'clip'] <- 'off'
      #grid.newpage()
      grid.draw(g)
      ggsave(paste(path, 
                   paste(graphnumber, filename, sep = "_"),sep = ""), 
             plot = g, width = 10, height = 5)}
    
  else{
      ggsave(paste(path, 
                   paste(graphnumber, filename, sep = "_"), sep = ""), width = 10, height = 5)
    }
  }
  
  else{
  g +
      #scale_y_continuous(breaks = seq(0,top_break, len = numb_ticks_accurate), oob = squish) + 
      ggsave(paste(path, paste(graphnumber, filename, sep = "_"),sep = ""), 
             width = 10, height = 5)
  }
}
```

```{r}
## function quantifies GDI
quantify_distortion_GDI <- function(selected_rows){
  
  cuttingat <- get_cuttingat(selected_rows, setGDI)
  d2<- max(selected_rows$Value)
  d1<- min(selected_rows$Value)
  g2 <- d2 - cuttingat
  g1 <- d1 - cuttingat
  
  a <- (g2 - g1)/(g1)
  b <- (d2-d1)/d1
  GDI <-  100* ((a/b) - 1)
  return(GDI)
}

## function quantifies RGD
quantify_distortion_RGD <- function(selected_rows){
  
  cuttingat <- get_cuttingat(selected_rows, setGDI)
  
  d2<- max(selected_rows$Value)
  d1<- min(selected_rows$Value)
  g2 <- d2 - cuttingat
  g1 <- d1 - cuttingat
  g3 <- (g1/d1)*d2
  RGD <- (g2 - g3)/g3
  
  return(RGD)
  }
```



#Run Functions
```{r}

# ######### RUN ONCE ######################
# #### The following lines create a data frame called
# #### all_graph_data that makes the graphs reproducible.
# 
# # #Create df to save graph_data used for each graph
# all_graph_data <- data.frame(matrix(NA, nrow = 0, ncol = ncol(data)))
#    colnames(all_graph_data) <- colnames(data)
# 
# # ## run get graph_data_sample once to select specific data points to use for each graph
# for(i in 1:(max(data[1]))) {
#   graph_data <- get_graph_data_sample(data, i)
#   all_graph_data <- rbind(all_graph_data, graph_data)}
# 
# write.csv(all_graph_data, file = "all_graph_data2.csv", row.names=FALSE)
# 
# #load filtered data (only the right amount of bars)
# all_graph_data <- read_csv("all_graph_data2.csv")
# 
# 
# # #Create df to save graph_data used for each graph
# all_selected_rows <- data.frame(matrix(NA, nrow = 0, ncol = ncol(all_graph_data)))
#    colnames(all_selected_rows) <- colnames(all_graph_data)
# 
# # # Fill in df with selected rows
# for(i in 1:(max(all_graph_data[1]))){
#   graph_data <- all_graph_data %>%
#     filter(graphcode == i)
#   chosen_2 <- choose_2(graph_data)
#   all_selected_rows <- rbind(all_selected_rows, chosen_2)}
# 
# write.csv(all_selected_rows, file = "all_selected_rows2.csv", row.names=FALSE)
# #
# # #load filtered data (only the right amount of bars)
# all_selected_rows <- read_csv("all_selected_rows2.csv")
```



```{r}
######### CREATE GRAPHS ######################
# Set GDI 
setGDI <- 500

#Create df to save distortion measurements
number_of_graphs <- c(1:max(data[1]))
distortion_data <- data.frame(number_of_graphs)

  
# plot for all data points in filtered data df
for(i in 1:(max(all_graph_data[1]))){
  graph_data <- all_graph_data %>% 
    filter(graphcode == i)
  
  selected_rows <- all_selected_rows %>% 
    filter(graphcode == i)
  
  graph(graph_data, selected_rows, i, "accurate", "graphs_set2/", "accurate.jpg", "none")
 graph(graph_data, selected_rows, i, "misleading", "graphs_set2/", "misleading.jpg", "none") 
# graph(graph_data, selected_rows, i, "misleading", "graphs_set2/", "misleading_highlight.png", "highlight") 
  
  
  distortion_data$max[i]<- max(selected_rows$Value)
  distortion_data$min[i]<- min(selected_rows$Value)
  distortion_data$difference[i] <- max(selected_rows$Value)-min(selected_rows$Value)
  distortion_data$percentage_change[i]<-(max(selected_rows$Value)-min(selected_rows$Value))/min(selected_rows$Value)
  distortion_data$GDI[i] <- quantify_distortion_GDI(selected_rows)
  distortion_data$RGD[i] <-quantify_distortion_RGD(selected_rows)
}

write.csv(distortion_data, file = "distortion_data2.csv", row.names=FALSE)
```

